### ISSUE TITLE
release 0.4.5 is not yet pushed to docker hub

### ISSUE THREAD

**Issue by chungmanau** [drycc-addons/service-catalog#20]
# Bug Report 

**What happened**:
I cannot pull 0.4.5 image from docker hub

**What you expected to happen**:
I expect to pull 0.4.5 image from docker hub

**How to reproduce it (as minimally and precisely as possible)**:
Execute _docker pull drycc/service-catalog:0.4.5_ get error
Error response from daemon: manifest for drycc/service-catalog:0.4.5 not found: manifest unknown: manifest unknown

Execute _docker pull registry.drycc.cc/drycc/service-catalog:0.4.5_ get error
Error response from daemon: unknown: artifact drycc/service-catalog:0.4.5 not found

p.s. I can execute _docker pull drycc/service-catalog:0.4.2_ without problem

**Anything else we need to know?**:
NA 

**Environment**:
- Kubernetes version (use `kubectl version`):
- service-catalog version:
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by duanhongyi** [comment]
The synchronization has been completed. docker.io may be discarded in the future.

see:
 registry.drycc.cc/drycc-addons/service-catalog:0.4.5
