### ISSUE TITLE
Version 0.4.6 had not been built and released yet

### ISSUE THREAD

**Issue by chungmanau** [drycc-addons/service-catalog#22]
# Bug Report 

**What happened**:
The golang version had been upgraded to 1.20 in https://github.com/drycc-addons/service-catalog/blob/main/Makefile#L60 
But it misses 2 things: no official release of 0.4.6 and pull it to docker hub.

**What you expected to happen**:
Has an official 0.4.6 release and pull it to docker hub.
 
**How to reproduce it (as minimally and precisely as possible)**:
Go to https://github.com/drycc-addons/service-catalog/releases/tag/v0.4.6 to check the builds

**Anything else we need to know?**:
After build 0.4.6, it is much better pull it to the docker hub.

**Environment**:
- Kubernetes version (use `kubectl version`):
- service-catalog version:
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by duanhongyi** [comment]
On Monday, March 24th, the docker.io registry will switch to registry.drycc.cc.

see:

`registry.drycc.cc/drycc-addons/service-catalog:0.4.6`
